# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mvn test
      - run: mvn sonar:sonar -Dsonar.projectKey=khoovirajsingh_gilded-rose-kata -Dsonar.organization=khoovirajsingh -Dsonar.host.url=https://sonarcloud.io Dsonar.login=2b161e0fc11913660d09c1e0f5f730e616881a03
